name: CI

on: [push]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: MSBuild
      working-directory: src
      run: msbuild -t:restore;rebuild WinKernelObjectsDotNet\WinKernelObjectsDotNet.csproj
    - name: Upload artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: upload debug-build artifacts
        path: src\WinKernelObjectsDotNet\bin\Debug\
    - name: Run a multi-line script
      run: |
        echo "completely done"
        echo the ende
